#!/usr/bin/bash

mkdir tempbajar;
cd tempbajar;
if [[ `youtube-dl $1` ]] ; then
	NAME=`ls`;
	NAMEFINAL=`youtube-dl --get-title $1`;
	NAMEWAV=`echo $NAME | sed "s/[^.]*$/wav/"`;
	#NAMEMP3=`echo $NAMEWAV | sed "s/.wav/.mp3/"`;
	NAMEMP3="$NAMEFINAL".mp3
	ffmpeg -i "$NAME" "$NAMEWAV";
	lame "$NAMEWAV" "$NAMEMP3";
	mv "$NAMEMP3" ../
	cd ../
	rm -rf tempbajar
else
	echo "Cannot find URL"
fi

